# Generated by Django 5.0.7 on 2024-07-20 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, unique=True)),
                ('order', models.CharField(max_length=255, unique=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.album')),
            ],
        ),
    ]
